### ISSUE TITLE
Iron Kinesis Pipe Energy Texture Issues

### ISSUE THREAD

**Issue by LuigiHutch** [AlexIIL/Buildcraft_1.8_Issues#95] opened 2016-01-14 22:55 UTC
Forge 11.15.0.1688
BC 7.2.0 Pre 6

The iron pipe energy texture seems to over fill the texture when it is limiting the power when it is recieving power from 2 or more sides:
![2016-01-14_22 30 14](https://cloud.githubusercontent.com/assets/9326429/12340185/2a83a918-bb11-11e5-89bb-7728319d7a15.png)

These two images also show some z-fighting with the energy texture but this may occur with all pipes, not just iron pipes:
![2016-01-14_22 45 49](https://cloud.githubusercontent.com/assets/9326429/12340186/2a897dfc-bb11-11e5-8128-babc1ba5ac88.png)
![2016-01-14_22 45 56](https://cloud.githubusercontent.com/assets/9326429/12340184/2a83b624-bb11-11e5-8f6f-6dbac2bd1c26.png)

**Comment by Xariyl** [comment] 2016-01-26 02:20
Tested with pre-7, and I no longer get this texture issue.

**Comment by AlexIIL** [comment] 2016-01-26 02:22
What? But I haven't touched pipe rendering code...

**Comment by Xariyl** [comment] 2016-01-26 02:23
I duplicated Luigi's setup and I don't see the glitch. I _did_ get it in pre-6 though. 

Maybe I have something else that's messing with it? I'm running multiple mods and the latest version of Forge (11.15.0.1718)

(edit - sorry, I listed the wrong forge version... updated with what I'm currently using in this profile)

**Comment by Xariyl** [comment] 2016-01-26 02:36
![Working Kinesis pipe](http://i.imgur.com/pkfrgZq.png?1)

I only took the one screenshot, but I looked at it from every angle, as Luigi did. <shrug> Works for me :smile:

**Comment by LuigiHutch** [comment] 2016-01-26 08:52
Still happens in Pre-7:
![2016-01-26_08 49 25](https://cloud.githubusercontent.com/assets/9326429/12576198/e0bd51d8-c409-11e5-9177-5733435217e5.png)

Engines on the right are outputting 1280rf/t and the iron kinesis pipe is limiting it to 20rf/t

**Comment by AEnterprise** [comment] 2016-01-26 19:54
could you guys use F3 and look at the pipe when making the screenshot? maybe the setup orientation has something to do with it

**Comment by Xariyl** [comment] 2016-01-26 21:10
Luigi's right. I know what I did wrong.

I forgot to max the engines' output :angry:
Sorry guys.

Scary to think troubleshooting is what I do for a living...

**Comment by LuigiHutch** [comment] 2016-01-26 23:56
To be fair, I didn't say what the engines were outputting. Also the first set up wasn't very clear :p

**Comment by Xariyl** [comment] 2016-01-27 00:29
lol... to be just as fair, we're talking about a power-restricting pipe that wasn't receiving enough power to restrict.

**Comment by AEnterprise** [comment] 2016-01-27 08:48
alright that's that part sorted out

**Comment by AlexIIL** [comment] 2016-01-27 18:34
Technically a duplicate of #62.

**Closed as completed by AlexIIL** 2016-01-27 18:34 UTC
Labels: bug

**Comment by LuigiHutch** [comment] 2016-01-27 20:03
So, I actually made a duplicate of my own issue :D
