### ISSUE TITLE
Issue with Chisel and JEI

### ISSUE THREAD

**Issue by Alaric323** [AlexIIL/Buildcraft_1.8_Issues#96] opened 2016-01-16 18:37 UTC
The end of a huge amount of console spam (Final log is about 30 Megabytes in size):
http://puu.sh/my25X/aa0bec2c92.txt

Only happens when chisel is installed.  I have the full log if you need it.  I originally posted this on Chisel's issues (like a derp), and they said an issue with logging errors.

**Comment by AlexIIL** [comment] 2016-01-16 18:47
Technically a duplicate of #93

**Closed as completed by AlexIIL** 2016-01-16 18:47 UTC
