### ISSUE TITLE
Crash when breaking block without breaking particle icon with a filler (probably a builder too)

### ISSUE THREAD

**Issue by primetoxinz** [AlexIIL/Buildcraft_1.8_Issues#75] opened 2015-12-21 03:23 UTC
http://paste.ee/p/cW89A

To reproduce, remove a chest with a filler

**Comment by AlexIIL** [comment] 2015-12-21 14:24
I cannot reproduce this in my dev environment with a chest. Can you update to pre4 (it came out very quickly afterwards, I won't make that mistake in the future) and see if it happens?

**Comment by primetoxinz** [comment] 2015-12-23 21:48
I can no longer reproduce it with chests on pre4, but blocks from Chisels And Bits crash the same way

**Comment by AlexIIL** [comment] 2015-12-23 22:38
Can you reproduce this with JUST BuildCraft pre1 and a chest? Because I am starting to think that this isn't BuildCraft's issue

**Comment by AlexIIL** [comment] 2015-12-28 21:49
I'm closing this for now but re-open if you can reproduce this is ONLY buildcraft

**Closed as completed by AlexIIL** 2015-12-28 21:49 UTC
Labels: help wanted, not buildcraft
