### ISSUE TITLE
Unable to place levers on  the back of engines

### ISSUE THREAD

**Issue by LuigiHutch** [AlexIIL/Buildcraft_1.8_Issues#63] opened 2015-12-17 22:36 UTC
Buildcraft 7.2.0 Prerelease 1

You are unable to place levers on  the back of engines

-LuigiHutch

**Comment by AlexIIL** [comment] 2015-12-18 20:41
technically a duplicate of #71 which is technically either a forge or a minecraft bug

**Closed as completed** 2015-12-18 20:41 UTC
