### ISSUE TITLE
Crash with Optifine loading textures *1.8.8 Dev4* -- java.lang.IllegalArgumentException: Wanted 28 data points, but found 56!

### ISSUE THREAD

**Issue by JonnyBrando** [AlexIIL/Buildcraft_1.8_Issues#80] opened 2015-12-28 19:14 UTC
Buildcraft crashes while loading if Optifine is present.

Major Mods:
Forge 11.15.0.1650, Optifine HD U 1.8.8 G9, Sildur's Vibrant v11 Extreme, ChromaHills 128x RP.

Error:
---- Minecraft Crash Report ----

WARNING: coremods are present:
  MMFMLCorePlugin (MultiMine-1.8.8.jar)
  DLFMLCorePlugin (DynamicLights-1.8.8.jar)
  SCFMLCorePlugin (StalkerCreepers-1.8.8.jar)
Contact their authors BEFORE contacting forge

// You should try our sister game, Minceraft!

Time: 12/28/15 2:04 PM
Description: Initializing game

java.lang.IllegalArgumentException: Wanted 28 data points, but found 56!
    at buildcraft.core.lib.render.BuildCraftBakedModel.replaceShade(BuildCraftBakedModel.java:296)
    at buildcraft.transport.render.PipeItemModel.create(PipeItemModel.java:53)
    at buildcraft.BuildCraftTransport.registerModels(BuildCraftTransport.java:728)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_72_BuildCraftTransport_registerModels_ModelBakeEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:55)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
    at net.minecraftforge.client.ForgeHooksClient.onModelBake(ForgeHooksClient.java:353)
    at net.minecraft.client.resources.model.ModelManager.func_110549_a(ModelManager.java:30)
    at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110544_b(SimpleReloadableResourceManager.java:130)
    at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110541_a(SimpleReloadableResourceManager.java:111)
    at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:740)
    at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:323)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:495)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:329)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at buildcraft.core.lib.render.BuildCraftBakedModel.replaceShade(BuildCraftBakedModel.java:296)
    at buildcraft.transport.render.PipeItemModel.create(PipeItemModel.java:53)
    at buildcraft.BuildCraftTransport.registerModels(BuildCraftTransport.java:728)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_72_BuildCraftTransport_registerModels_ModelBakeEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:55)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
    at net.minecraftforge.client.ForgeHooksClient.onModelBake(ForgeHooksClient.java:353)
    at net.minecraft.client.resources.model.ModelManager.func_110549_a(ModelManager.java:30)
    at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110544_b(SimpleReloadableResourceManager.java:130)
    at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110541_a(SimpleReloadableResourceManager.java:111)
    at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:740)
    at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:323)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:495)

-- Initialization --
Details:
Stacktrace:
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:329)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.8.8
    Operating System: Windows 10 (amd64) version 10.0
    CPU: 4x Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz
    Java Version: 1.8.0_66, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 856401152 bytes (816 MB) / 2048122880 bytes (1953 MB) up to 2120679424 bytes (2022 MB)
    JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms350m -Xmx2G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -XX:+AggressiveOpts -Xmn256M
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP 9.18 Powered by Forge 11.15.0.1650 Optifine OptiFine_1.8.8_HD_U_G9 24 mods loaded, 24 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJA  mcp{9.18} [Minecraft Coder Pack](minecraft.jar) 
    UCHIJA  FML{8.0.99.99} [Forge Mod Loader](forge-1.8.8-11.15.0.1650-1.8.8.jar) 
    UCHIJA  Forge{11.15.0.1650} [Minecraft Forge](forge-1.8.8-11.15.0.1650-1.8.8.jar) 
    UCHIJA  Baubles{1.1.2.0} [Baubles](Baubles-1.8.8-1.1.2.0.jar) 
    UCHIJA  BuildCraft|Core{7.2.0pre4} [BuildCraft](buildcraft-1.8.8-7.2.0pre4.jar) 
    UCHIJA  BuildCraft|Transport{7.2.0pre4} [BC Transport](buildcraft-1.8.8-7.2.0pre4.jar) 
    UCHIJA  BuildCraft|Factory{7.2.0pre4} [BC Factory](buildcraft-1.8.8-7.2.0pre4.jar) 
    UCHIJA  BuildCraft|Silicon{7.2.0pre4} [BC Silicon](buildcraft-1.8.8-7.2.0pre4.jar) 
    UCHIJA  BuildCraft|Robotics{7.2.0pre4} [BC Robotics](buildcraft-1.8.8-7.2.0pre4.jar) 
    UCHIJA  BuildCraft|Energy{7.2.0pre4} [BC Energy](buildcraft-1.8.8-7.2.0pre4.jar) 
    UCHIJA  BuildCraft|Builders{7.2.0pre4} [BC Builders](buildcraft-1.8.8-7.2.0pre4.jar) 
    UCHIJA  customnpcs{1.8.8_beta} [CustomNPCs](CustomNpcs_1.8.8_beta%2817dec15%29.jar) 
    UCHIJA  DynamicLights{1.3.9} [Dynamic Lights](DynamicLights-1.8.8.jar) 
    UCHIJA  DynamicLights_onFire{1.0.5} [Dynamic Lights Burning Entity Module](DynamicLights-1.8.8.jar) 
    UCHIJA  DynamicLights_creepers{1.0.4} [Dynamic Lights Creeper Module](DynamicLights-1.8.8.jar) 
    UCHIJA  DynamicLights_dropItems{1.0.8} [Dynamic Lights EntityItem Module](DynamicLights-1.8.8.jar) 
    UCHIJA  DynamicLights_entityClasses{1.0.1} [Dynamic Lights Entity Light Module](DynamicLights-1.8.8.jar) 
    UCHIJA  DynamicLights_mobEquipment{1.0.8} [Dynamic Lights Mob Equipment Light Module](DynamicLights-1.8.8.jar) 
    UCHIJA  DynamicLights_flameArrows{1.0.0} [Dynamic Lights Fiery Arrows Light Module](DynamicLights-1.8.8.jar) 
    UCHIJA  DynamicLights_floodLights{1.0.2} [Dynamic Lights Flood Light](DynamicLights-1.8.8.jar) 
    UCHIJA  DynamicLights_otherPlayers{1.0.7} [Dynamic Lights OtherPlayers Light Module](DynamicLights-1.8.8.jar) 
    UCHIJA  DynamicLights_thePlayer{1.1.3} [Dynamic Lights Player Light Module](DynamicLights-1.8.8.jar) 
    UCHIJA  AS_MultiMine{1.5.0} [Multi Mine](MultiMine-1.8.8.jar) 
    UCHIJA  VersionChecker{1.2.5} [Version Checker](VersionChecker-1.2.5.jar) 
    Loaded coremods (and transformers): 
MMFMLCorePlugin (MultiMine-1.8.8.jar)
  atomicstryker.multimine.common.fmlmagic.MMTransformer
DLFMLCorePlugin (DynamicLights-1.8.8.jar)
  atomicstryker.dynamiclights.common.DLTransformer
SCFMLCorePlugin (StalkerCreepers-1.8.8.jar)
  atomicstryker.stalkercreepers.common.SCTransformer
    GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 354.42' Renderer: 'Quadro K620M/PCIe/SSE2'
    Launched Version: 1.8.8-forge1.8.8-11.15.0.1650-1.8.8
    LWJGL: 2.9.4
    OpenGL: Quadro K620M/PCIe/SSE2 GL version 4.5.0 NVIDIA 354.42, NVIDIA Corporation
    GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

```
Using VBOs: Yes
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: ChromaHills-128x1.8_OptifineLeavesFix.zip, ChromaHills-128x1.8_v.12.zip
Current Language: English (US)
Profiler Position: N/A (disabled)
CPU: 4x Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz
```

Logs:
https://dl.dropboxusercontent.com/u/14381275/BuildCraft_1.8.8_Optifine_Crash.zip
https://dl.dropboxusercontent.com/u/14381275/BuildCraft_1.8.8_NoOF_Working.zip

**Comment by AlexIIL** [comment] 2015-12-28 21:32
Try disabling shaders?

**Comment by AlexIIL** [comment] 2015-12-28 21:37
On a side not optifine is NOT supported by 1.7.10 versions of BC and its probably not compatable with 1.8.8 versions either. Not an awful lot I can do about that, sorry :/

**Comment by JonnyBrando** [comment] 2015-12-29 01:58
I've used Optifine with every version from 1.4.6 to 1.8 without problems.

I'm currently using Optifine 1.7.10 HD U C1 + ShadersMod 2.3.28 (independently) with 1.7.10, and Optifine 1.8.0 HD U G9 (includes Shaders just like 1.8.8) with 1.8. Works just fine.

This should be a bug that you can fix, it doesn't exist in the 1.8 version of Beta 0.10.

**Comment by JonnyBrando** [comment] 2015-12-29 02:04
If I turn off the shaderpack, it works fine.

I would push the bug report to sp614x, but considering that OF 1.8 HD U G9 and OF 1.8.8 HD U G9 both probably have extremely similar code, and BuildCraft 1.8 Beta 0.10 works...

I would have a tendency to leave it here, but I will link this thread to sp614x just in case.

**Comment by AlexIIL** [comment] 2015-12-29 02:11
Buildcraft for 1.8 had less features than 7.2.0pre4 so I'm not surprised it didn't work. I think I can fix this but it requires a refactor of the model generation code, which is not a trivial thing at all.

**Comment by asiekierka** [comment] 2015-12-29 13:09
This is most likely because of the WorldRenderer stuff. Wasn't that introduced inbetween versions, and didn't 1.8.0 still have a Tessellator?

Either way, do push the bug report to sp614x anyway. If anything, he knows how OptiFine works and we don't because it's _closed-source_.

**Comment by AlexIIL** [comment] 2015-12-29 13:11
Its caused by their changes to BakedQuad (Specifically they expand a normal 4x7 int array into a 4x14 int array if shaders are enabled.) Ideally they should be using their own method instead of expanding the array in place so that mods don't get confused by the incorrect length

**Comment by asiekierka** [comment] 2015-12-29 13:56
@AlexIIL - Do they change the VertexFormat? If so, offsets can be calculated, like I do in Charset...

**Comment by AlexIIL** [comment] 2015-12-29 14:05
Nope. They change the constructor of BakedQuad to 

``` java
public BakedQuad(int[] vertexData, int tintIndex, EnumFacing face) {
    this.vertexData = fixVertexData(vertexData);
    this.tintIndex = tintIndex;
    this.face = face;
}

private static int[] fixVertexData(int[] vd) {
  if (Config.isShaders()) {
    if (vd.length == 28) {
      // Function that changes the array from length 28 to length 56
      vd = expandVertexData(vd);
    }
  } else if (vd.length == 56) {
    // Function that changes the array from length 56 to length 28
    vd = compactVertexData(vd);
  }
  return vd;
}
```

(I cannot find any optifine license that stops me from using a decompiler but if any optifine person can point me to an offical EULA or other copyright agreement that I am reading incorrectly please notify me)

**Comment by AlexIIL** [comment] 2015-12-29 14:09
I have no idea if they independently change DefaultVertexFormats or not but I assume not. My plan was to use UnpackedBakedQuad instead of the normal BakedQuad to fix this (and then the code doesn't require a specific length)

**Comment by JonnyBrando** [comment] 2015-12-31 00:12
There appears to be another fix, here is sp614x's answer:

http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1272953-optifine-hd-g9-fps-boost-hd-textures-shaders-and?comment=48991

This is a BuildCraft problem, it conflicts with the shaders vertex format size.
It should use a variable vertex format size "vertexData.length / 4", not fixed (28 / 4).
There is no workaround possible, the shaders require double vertex format size in order to work.

**Comment by AlexIIL** [comment] 2015-12-31 00:20
Thanks. I'll ask him about fixes and how optifine works :)

**Comment by JonnyBrando** [comment] 2016-01-02 02:34
Thanks, Alex!

Great work so far! Keep it up!

**Comment by AlexIIL** [comment] 2016-01-03 23:02
Can you try this with pre5? I released it here (for 1.8.8, but it ALSO works with forge for 1.8.9).
(7.2.0pre5) https://www.dropbox.com/s/9lmr1a3jzd9g9l...5.jar?dl=1

**Comment by JonnyBrando** [comment] 2016-01-05 20:49
I'll take a boo tonight and make sure that it is working in 1.8.8 and 1.8.9.

Had to grab the link from the forums, it concatenated the URL:
https://www.dropbox.com/s/9lmr1a3jzd9g9lo/buildcraft-7.2.0pre5.jar?dl=1

**Comment by JonnyBrando** [comment] 2016-01-05 20:50
Is the new pre6 both 1.8.8 and 1.8.9 compatible as well?

https://www.dropbox.com/s/q1qppz3sq447173/buildcraft-7.2.0-pre6.jar?dl=1

**Comment by AlexIIL** [comment] 2016-01-05 20:56
Just 1.8.9.

**Comment by AlexIIL** [comment] 2016-03-13 17:06
This should be fixed by now.

**Closed as completed by AlexIIL** 2016-03-13 17:06 UTC
Labels: bug
