### ISSUE TITLE
Gate GUI Text issue

### ISSUE THREAD

**Issue by LuigiHutch** [AlexIIL/Buildcraft_1.8_Issues#65] opened 2015-12-18 00:14 UTC
Buildcraft 7.2.0 Prerelease 1
Weird text issue in BC gui's. See Image:
![2015-12-17_23 44 50](https://cloud.githubusercontent.com/assets/9326429/11885935/1d883ed2-a51c-11e5-865e-4b39287a3a05.png)

This does not happen in vanilla gui's that I tested so it can't be JEI.
-LuigiHutch

Edit: can to can't

**Comment by AlexIIL** [comment] 2015-12-18 00:17
Looks like I am not clearing to alpha. Woops!

**Comment by LuigiHutch** [comment] 2016-01-31 23:32
Fixed :D

**Comment by AlexIIL** [comment] 2016-01-31 23:51
I... what? where? how did I fix this?

**Comment by AlexIIL** [comment] 2016-01-31 23:51
(I must have fixed this by accident by cleaning up one of the renderers)

**Comment by LuigiHutch** [comment] 2016-01-31 23:53
Yh, I couldn't reproduce it in pre 10 but it was probably fixed in prior versions :)

**Comment by AlexIIL** [comment] 2016-02-01 15:39
Is this what you call fixed?

EDIT: That was meant to be sarcastic, sorry :/.
![screenshot from 2016-02-01 15 37 39](https://cloud.githubusercontent.com/assets/3751138/12721914/07e72ce4-c8fa-11e5-9e72-82e739f4932f.png)

**Comment by LuigiHutch** [comment] 2016-02-01 15:49
How? I couldn't reproduce it :/

**Comment by AlexIIL** [comment] 2016-02-01 16:03
A bit of background: the gate GUI itself doesn't cause the issue, one of the OTHER tile entity renderers (say, a quarry) doesn't do something quite right which causes this. The fix is then not the gate GUI itself, but the tile (which may be different as this happened in my dev environment rather than strictly in pre10)

**Comment by MrGraphic** [comment] 2016-02-01 16:43
Oh my. While you are looking at this you my want to check rest of the triggers - some of the triggers have missing textures like enrgy levels :).

**Comment by AlexIIL** [comment] 2016-02-01 16:53
@MrGraphic  Can you screen-shot your missing triggers please? They all exist for me, but some might have bugged outside of my dev environment.
![screenshot from 2016-02-01 16 51 00](https://cloud.githubusercontent.com/assets/3751138/12724087/428d1fa2-c904-11e5-9fcf-263cd8c127bb.png)

**Comment by MrGraphic** [comment] 2016-02-01 17:21
Yeah sure, It my be caused by active resource pack ( vanilla only but 32x ). I will check and return to you.

**Comment by MrGraphic** [comment] 2016-02-01 17:37
Oh my - not energy but fuel/coolant levels, sorry. BTW cool "fix" for invisible pipes hehe :D - at least they are visible now ;) ..
![miss_trigg](https://cloud.githubusercontent.com/assets/4780141/12725360/42d49d86-c90a-11e5-8a0b-73d581a09f84.jpg)

**Comment by AlexIIL** [comment] 2016-03-13 17:08
HOPEFULLY this has been fixed now. reopen on the main issue repo if it happens again

**Closed as completed by AlexIIL** 2016-03-13 17:08 UTC
Labels: bug
