### ISSUE TITLE
Facade crash with JEI

### ISSUE THREAD

**Issue by mezz** [AlexIIL/Buildcraft_1.8_Issues#93] opened 2016-01-14 00:19 UTC
When JEI loads it calls `ItemModelMesher.getItemModel` on each itemStack to see if it has a valid item model. Tons of facades just crash on this call, instead of returning no model.
The crash is caught by JEI and logged to console:
http://pastebin.com/Fup8tNf9
By default JEI hides items with no model or broken models. To see these facades in JEI, you can go into the options and disable this feature under advanced settings.

Originally reported here: https://github.com/mezz/JustEnoughItems/issues/108

When a recipe is looked up for these items, it causes a crash.
Originally reported here: https://github.com/mezz/JustEnoughItems/issues/109

**Comment by mezz** [comment] 2016-01-14 05:27
It looks like this is most likely a bad interaction between Buildcraft facades and Chisel blocks.
https://github.com/mezz/JustEnoughItems/issues/113

**Comment by TSM-EVO** [comment] 2016-01-15 01:34
I also get this, log similar to this: http://pastebin.com/FENwXu70

**Comment by AEnterprise** [comment] 2016-01-15 20:38
it's a known issue with the BC facadec since they where first added, for most blocks they work fine but when blocks start using special renders thing can get wonky

**Comment by AlexIIL** [comment] 2016-01-16 00:38
Facade rendering needs to be redone (completly) to make it work with normal block models. At the moment there is a single model for all solid facades, and I just use the particle sprite of the target model to make it work. This crash is basically caused by the sprite being null instead of a texture. (This is nothing todo with previous versions of BC)

**Comment by LuigiHutch** [comment] 2016-01-28 14:04
Confirmed Fixed in Pre-7

**Closed as completed** 2016-03-13 17:04 UTC
Labels: Fixed in latest
